apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: expense
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: expense
  DB_NAME: transactions
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    tier: api
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      tier: api
      app: backend
  template:
    metadata:
      labels:
        project: expense
        tier: api
        app: backend
    spec:
      containers:
        - name: backend
          image: srlaf/backend:a1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    tier: api
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080